module.exports = (sequelize, DataTypes) => {
    const User = sequelize.define('Users', {
      login_uuid: {
        type: DataTypes.STRING,
        primaryKey: true,
        allowNull: false,
        autoIncrement: false,
      },
      login_username: DataTypes.STRING,
      login_password: DataTypes.STRING,
      login_salt: DataTypes.STRING,
      login_md5: DataTypes.STRING,
      login_sha1: DataTypes.STRING,
      login_sha256: DataTypes.STRING,
      name_title: DataTypes.STRING,
      name_title: DataTypes.STRING,
      name_first: DataTypes.STRING,
      name_last: DataTypes.STRING,
      gender: DataTypes.STRING,
      location_street_number : DataTypes.INTEGER,
      location_street_name : DataTypes.STRING,
      location_city : DataTypes.STRING,
      location_state : DataTypes.STRING,
      location_country : DataTypes.STRING,
      location_postcode : DataTypes.STRING,
      location_coordinates_latitude : DataTypes.STRING,
      location_coordinates_longitude : DataTypes.STRING,
      location_timezone_offset : DataTypes.STRING,
      location_timezone_description : DataTypes.STRING,
      email : DataTypes.STRING,
      dob_date : DataTypes.STRING,
      dob_age : DataTypes.INTEGER,
      registered_date : DataTypes.STRING,
      registered_age : DataTypes.INTEGER,
      phone : DataTypes.STRING,
      cell : DataTypes.STRING,
      id_name : DataTypes.STRING,
      id_value : DataTypes.STRING,
      picture_large : DataTypes.STRING,
      picture_medium : DataTypes.STRING,
      picture_thumbnail : DataTypes.STRING,
    });
  
    return User;
  };